# Generated by Django 5.2.11 on 2026-02-06 05:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="India", max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "website",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "total_capacity",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Total capacity of the center",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("has_indoor_facility", models.BooleanField(default=True)),
                ("has_outdoor_facility", models.BooleanField(default=False)),
                ("has_parking", models.BooleanField(default=False)),
                ("has_food_court", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center_head",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user assigned as Center Head",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_centers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Center",
                "verbose_name_plural": "Centers",
                "db_table": "centers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CenterFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("gym", "Gymnasium"),
                            ("pool", "Swimming Pool"),
                            ("track", "Running Track"),
                            ("court", "Sports Court"),
                            ("field", "Athletic Field"),
                            ("dojo", "Dojo/Martial Arts"),
                            ("classroom", "Classroom"),
                            ("cafeteria", "Cafeteria"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="centers.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "Center Facility",
                "verbose_name_plural": "Center Facilities",
                "db_table": "center_facilities",
            },
        ),
        migrations.AddIndex(
            model_name="center",
            index=models.Index(
                fields=["city", "is_active"], name="centers_city_d498af_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="centerfacility",
            unique_together={("center", "facility_type")},
        ),
    ]
