# Generated by Django 5.2.11 on 2026-02-06 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("athlete_portal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=True, help_text="Is this the primary emergency contact?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent",
                "verbose_name_plural": "Parents",
                "db_table": "parents",
            },
        ),
        migrations.CreateModel(
            name="ParentChildRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("mother", "Mother"),
                            ("father", "Father"),
                            ("guardian", "Guardian"),
                            ("grandparent", "Grandparent"),
                            ("other", "Other"),
                        ],
                        default="parent",
                        max_length=50,
                    ),
                ),
                (
                    "can_view_scores",
                    models.BooleanField(
                        default=True, help_text="Can view child's scores and results"
                    ),
                ),
                (
                    "can_view_rankings",
                    models.BooleanField(
                        default=True,
                        help_text="Can view child's rankings (only for 12+)",
                    ),
                ),
                (
                    "can_view_certificates",
                    models.BooleanField(
                        default=True, help_text="Can view child's certificates"
                    ),
                ),
                (
                    "can_view_attendance",
                    models.BooleanField(
                        default=True, help_text="Can view training session attendance"
                    ),
                ),
                (
                    "can_view_fees",
                    models.BooleanField(
                        default=False, help_text="Can view fee and payment information"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="athlete_portal.athleteperson",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="parent_portal.parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent Child Relation",
                "verbose_name_plural": "Parent Child Relations",
                "db_table": "parent_child_relations",
                "ordering": ["child__last_name", "child__first_name"],
                "unique_together": {("parent", "child")},
            },
        ),
    ]
