# Generated by Django 5.2.11 on 2026-02-06 05:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteeringOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField()),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("event_support", "Event Support"),
                            ("coaching", "Coaching Assistant"),
                            ("admin", "Administrative"),
                            ("maintenance", "Maintenance"),
                            ("coaching_mentorship", "Coaching Mentorship"),
                        ],
                        default="event_support",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "required_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=4,
                        help_text="Expected hours for this opportunity",
                        max_digits=5,
                    ),
                ),
                (
                    "required_skills",
                    models.CharField(
                        blank=True, help_text="Comma-separated list", max_length=500
                    ),
                ),
                ("min_age", models.PositiveIntegerField(default=16)),
                (
                    "max_volunteers",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("current_volunteers", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for Volunteers"),
                            ("closed", "Closed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteering_opportunities",
                        to="centers.center",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteering Opportunity",
                "verbose_name_plural": "Volunteering Opportunities",
                "db_table": "volunteering_opportunities",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True, help_text="Why volunteer is interested"
                    ),
                ),
                (
                    "experience",
                    models.TextField(blank=True, help_text="Relevant experience"),
                ),
                (
                    "hours_completed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Hours actually volunteered",
                        max_digits=5,
                    ),
                ),
                ("approval_notes", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_volunteer_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="volunteering.volunteeringopportunity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer Application",
                "verbose_name_plural": "Volunteer Applications",
                "db_table": "volunteer_applications",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.AddIndex(
            model_name="volunteeringopportunity",
            index=models.Index(
                fields=["center", "status"], name="volunteerin_center__99a1bd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="volunteerapplication",
            unique_together={("opportunity", "volunteer")},
        ),
    ]
