# Generated by Django 5.2.11 on 2026-02-06 05:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centers", "0001_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AthletePerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="Any known allergies"),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True, help_text="Any relevant medical conditions"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athletes",
                        to="centers.center",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional: link to user account if athlete has login",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="athlete_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Athlete",
                "verbose_name_plural": "Athletes",
                "db_table": "athlete_persons",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="AthleteRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Age group or skill category (e.g., U-12, Intermediate)",
                        max_length=100,
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Overall rank in category",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("events_participated", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking",
                        to="athlete_portal.athleteperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Athlete Ranking",
                "verbose_name_plural": "Athlete Rankings",
                "db_table": "athlete_rankings",
            },
        ),
        migrations.CreateModel(
            name="AthleteScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The score achieved",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "score_type",
                    models.CharField(
                        choices=[
                            ("points", "Points"),
                            ("time", "Time (seconds)"),
                            ("distance", "Distance (meters)"),
                            ("rank", "Rank/Position"),
                        ],
                        default="points",
                        max_length=50,
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, help_text="Placement/rank in event", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="athlete_portal.athleteperson",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athlete_scores",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Athlete Score",
                "verbose_name_plural": "Athlete Scores",
                "db_table": "athlete_scores",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Certificate title (e.g., Gold Medal)", max_length=255
                    ),
                ),
                ("description", models.TextField()),
                ("certificate_number", models.CharField(max_length=100, unique=True)),
                ("issued_date", models.DateField(auto_now_add=True)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "is_viewable_by_parents",
                    models.BooleanField(
                        default=True,
                        help_text="Can parents/guardians view this certificate?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="athlete_portal.athleteperson",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="events.event",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Certificate",
                "verbose_name_plural": "Evaluation Certificates",
                "db_table": "evaluation_certificates",
                "ordering": ["-issued_date"],
            },
        ),
        migrations.AddIndex(
            model_name="athleteperson",
            index=models.Index(
                fields=["center", "is_active"], name="athlete_per_center__19458c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="athletescore",
            unique_together={("athlete", "event")},
        ),
    ]
