# Generated by Django 5.2.11 on 2026-02-06 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("athlete_portal", "0001_initial"),
        ("centers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specializations",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list (e.g., Sprint, Long Jump, Relay)",
                        max_length=500,
                    ),
                ),
                (
                    "certifications",
                    models.TextField(blank=True, help_text="Coaching certifications"),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of coaching experience"
                    ),
                ),
                (
                    "is_head_coach",
                    models.BooleanField(
                        default=False, help_text="Is this a head coach for the center?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coaches",
                        to="centers.center",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach Profile",
                "verbose_name_plural": "Coach Profiles",
                "db_table": "coach_profiles",
            },
        ),
        migrations.CreateModel(
            name="CompetitionTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        help_text="Team category (e.g., U-14, U-18)", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("forming", "Forming"),
                            ("active", "Active"),
                            ("competing", "Competing"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="forming",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_teams",
                        to="coach_portal.coachprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Competition Team",
                "verbose_name_plural": "Competition Teams",
                "db_table": "competition_teams",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("athlete", "Athlete"),
                            ("alternate", "Alternate"),
                            ("reserve", "Reserve"),
                        ],
                        default="athlete",
                        max_length=20,
                    ),
                ),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="athlete_portal.athleteperson",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coach_portal.competitionteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "db_table": "team_members",
                "unique_together": {("team", "athlete")},
            },
        ),
        migrations.AddField(
            model_name="competitionteam",
            name="athletes",
            field=models.ManyToManyField(
                related_name="teams",
                through="coach_portal.TeamMember",
                to="athlete_portal.athleteperson",
            ),
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Session notes/feedback"),
                ),
                (
                    "attendance",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of athletes who attended",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "athletes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="training_sessions",
                        to="athlete_portal.athleteperson",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_sessions",
                        to="centers.center",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_sessions",
                        to="coach_portal.coachprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Session",
                "verbose_name_plural": "Training Sessions",
                "db_table": "training_sessions",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["coach", "status"],
                        name="training_se_coach_i_55333d_idx",
                    ),
                    models.Index(
                        fields=["start_time", "status"],
                        name="training_se_start_t_498b9d_idx",
                    ),
                ],
            },
        ),
    ]
